services:
  - type: web
    name: NayaDost-2
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install --no-audit --no-fund
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: DB_DIR
        value: /var/data
    autoDeployTrigger: commit
    disk:
      name: nyd-data
      mountPath: /var/data
      sizeGB: 1
